var router = require('express').Router();
var fs = require('fs'); //This module allows to work witht the file system: read and write files back
var xmlParse = require('xslt-processor').xmlParse; //This module allows us to work with XML files
var xsltProcess = require('xslt-processor').xsltProcess; //The same module allows us to utilise XSL Transformation

//We define the root of our website and render index.html located inside the views folder
router.get('/', function(req, res) {
  res.render('index');
});

//We define a new route /get/html to be rendering our HTML table that is being generated by applying XSL file to XML
router.get('/get/html', function(req, res) {
    res.writeHead(200, {'Content-Type': 'text/html'}); //We are responding to the client that the content served back is HTML and the it exists (code 200)
    var xml = fs.readFileSync('CarCollection.xml', 'utf8'); //We are reading in the XML file
    var xsl = fs.readFileSync('CarCollection.xsl', 'utf8'); //We are reading in the XSL file
    var doc = xmlParse(xml); //Parsing our XML file
    var stylesheet = xmlParse(xsl); //Parsing our XSL file
    var result = xsltProcess(doc, stylesheet); //Execute Transformation
    res.end(result.toString()); //We render the result back to the user converting it to a string before serving
});

module.exports = router;